version: '3.9'

services:
  # ==========================
  # NestJS Backend Service
  # ==========================
  # backend:
  #   container_name: artistic_backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5000:5000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #   networks:
  #     - backend-network
  #   restart: unless-stopped
  #   command: npm run start:dev

  # ==========================
  # Redis (for cache + queues)
  # ==========================
  redis:
    container_name: redis
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    restart: unless-stopped

  # ==========================
  # RedisInsight (optional UI)
  # ==========================
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    networks:
      - backend-network
    depends_on:
      - redis
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
